name: Build and publish to Github Pages

on:
  push:
    branches:
      - main
  workflow_dispatch: {}
  schedule:
    # Monday midnight
    - cron: '0 0 * * 1'

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.PUBLISH_TOKEN }}
          target-branch: 'gh-pages'